name: Build and Deploy Web App
on:
  push:
    branches:
      - main # Déclenchement lors d'un push sur la branche main

permissions:
  id-token: write
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        run: |
          az login --service-principal \
            -u ${{ secrets.AZURE_CLIENT_ID }} \
            -p ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-calicot-dev-${{ secrets.CODE_IDENTIFICATION }}'
          slot-name: 'production'
          package: '.' # Dossier contenant le code de l'application
